<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerS8tmere\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerS8tmere/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerS8tmere.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerS8tmere\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerS8tmere\appProdProjectContainer([
    'container.build_hash' => 'S8tmere',
    'container.build_id' => '42ea3266',
    'container.build_time' => 1640444535,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerS8tmere');
